export const data = [
  {
    id: 1,
    name: 'Germany',
    capital: 'Berlin',
    language: 'German',
    currency: 'EUR',
  },
  {
    id: 2,
    name: 'Austria',
    capital: 'Wien',
    language: 'German',
    currency: 'EUR',
  },
  {
    id: 3,
    name: 'France',
    capital: 'Paris',
    language: 'French',
    currency: 'EUR',
  },
  {
    id: 4,
    name: 'Spain',
    capital: 'Madrid',
    language: 'Spanish',
    currency: 'EUR',
  },
  {
    id: 5,
    name: 'Italy',
    capital: 'Rome',
    language: 'Italian',
    currency: 'EUR',
  },
  {
    id: 6,
    name: 'Finland',
    capital: 'Helsinki',
    language: 'Finnish',
    currency: 'EUR',
  },
  {
    id: 7,
    name: 'Sweden',
    capital: 'Stockholm',
    language: 'Swedish',
    currency: 'EUR',
  },
  {
    id: 8,
    name: 'Netherlands',
    capital: 'Amsterdam',
    language: 'Dutch',
    currency: 'EUR',
  },
  {
    id: 9,
    name: 'Czech',
    capital: 'Prague',
    language: 'Czech',
    currency: 'EUR',
  },
  {
    id: 10,
    name: 'Switzerland',
    capital: 'Bern',
    language: 'German, French, Italian',
    currency: 'CHF',
  },
  {
    id: 11,
    name: 'Greece',
    capital: 'Athens',
    language: 'Greek',
    currency: 'EUR',
  },
  {
    id: 12,
    name: 'Poland',
    capital: 'Warsaw',
    language: 'Polish',
    currency: 'PLN',
  },
]
